### ISSUE TITLE
Running Seeks

### ISSUE THREAD

**Issue by GyorgyO** [beniz/seeks#10]
Hello.
I cannot get Seeks to run. I enter cd src ./seeks or ./seeks and the 32 bit Cygwin console replies 'no such file or directroy'. I know only a very little about Unix. I am on 64 bit Windows Home Premium.
Thank you for any help,
GyorgyO

**Comment by beniz** [comment]
You need to give more information: how it was compiled, what compilation did say, etc... Please note that I am not sure anyone has run it on Windows. I also suspect that depending on how you want to use Seeks there are good chances that it won't run fine on Windows, even with Cygwin.

**Comment by GyorgyO** [comment]
Thank you beniz.

Do you know of anything like 'Seeks' that will run on Windows 7 ?

Thanks again.
GyorgyO

**Comment by beniz** [comment]
You might want to try java written [Yacy](http://yacy.net/en/index.html) though you might be deceived by the results.
