### ISSUE TITLE
Add seeks.hermes-net.de

### ISSUE THREAD

**Issue by GreenLunar** [beniz/seeks#19]
https://github.com/beniz/seeks/wiki/List-of-Web-Seeks-nodes

```
=== seeks.hermes-net.de ===
* HTTPS: <div class='monitor email@address'>https://seeks.hermes-net.de/</div>  
* Hidden Service: <div class='monitor email@address'>http://oq7hx5d4ip24ay2f.onion/</div>  
* Owner: email at address
* Running: 0.4.1-stable                                                  
* Options: no background content analysis (faster), image with safesearch on, clustering, similarity
* Server Options: IPv4, SSL
* Language: many
```

I would do it myself, but GitHub thinks I am not a human:

> **One of our mostly harmless robots seems to think you are not a human.**
> Because of that, it's hidden your profile from the public. If you really are human, please [contact support](https://github.com/support) to have your profile reinstated.
> We promise we won't require DNA proof of your humanity.

**Comment by GreenLunar** [comment]
Added.  Please review my changes.  See [History for List of Web Seeks nodes](https://github.com/beniz/seeks/wiki/List-of-Web-Seeks-nodes/_history).

**Comment by beniz** [comment]
thanks @GreenLunar I very much appreciate the effort!

**Comment by Quix0r** [comment]
Jun 30 21:43:46.913 7f8722ffd700 Error: curl error on url seeks.hermes-net.de/find_bqc?output=json: SSL: certificate subject name (www.hermes-net.de) does not match target host name 'seeks.hermes-net.de'

Edit: Okay, with http it seems to work.
Edit2: No, the same thing.

**Comment by Quix0r** [comment]
I cannot add it for peer-to-peer communication until the SSL issue has been fixed.

**Comment by GreenLunar** [comment]
@beniz, you are welcome!

@Quix0r, try to contact Hermes at http://soup.hermes-net.de/

**Comment by Quix0r** [comment]
Now I get "Service Temporarily Unavailable"
