### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [beniz/seeks#26]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/beniz/seeks/blob/9a74a298dde8706055859cc45a3708bb9a881610/src/seeks.cpp#L47)" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706)?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108) like they are described by Danny Kalev?

**Comment by beniz** [comment]
Thanks  for your work, but dev on this software has halted long ago, they'll be no fix nor changes unfortunately.

**Comment by GreenLunar** [comment]
@beniz, then open an organization at github.com/Seeks and let new developers join there.

Please do not ignore this issue. Seeing some recent and dated activity, even if not commits, would more likely to get others involved.

**Comment by GreenLunar** [comment]
Please merge this Pull Request.  Seeing some recent and dated activity would more likely to get others involved.

**Comment by Quix0r** [comment]
He's right. If you don't want to continue this (why, if I may ask?) then please let others continue.

**Comment by beniz** [comment]
Guys, anyone can submit a PR, but no one does. Elfring and I know each other, he's fact checking all the C++ programs out there, this has nothing to do with having new developers.

**Comment by elfring** [comment]
> Guys, anyone can submit a PR, but no one does.

Is any more drumming needed for additional contributors?

> Elfring and I know each other, …

I find that this feedback can be interpreted a bit too much at the moment. I am curious if such a kind of knowledge could be extended.

**Comment by beniz** [comment]
Guys, this software has taken a few good years of my life. It has been dead for many years now. [searx](https://github.com/asciimoo/searx) is the natural and very much popular follow up. This is a reality that needs to be swallowed, as hard as it seems it can be for some users, and I definitely understand the pain, I've been there and had to deal with it myself.

Please stop the harassment and whinning and go help the aforementioned `searx` with all your strength! I'll go there myself as soon as I get enough time and attention to do so.

There are many out there who have not given up on decentralized, privacy-oriented search, and it will happen if all get together in the same place.

Thanks.

**Comment by GreenLunar** [comment]
> There are many out there who have not given up on decentralized, privacy-oriented search, and it will happen if all get together in the same place.

This might be true, yet this is not what I worry about.

We do not attempt to harass you, all we (or at least myself) ask is to  relocate the source code of Seeks in some sort of a shared hub, a place where people would collaboratively seek a way to continue Seeks.

Moreover, the quality of code is not something I worry about, there is even a program called [PhotoQt](http://PhotoQt.org/) that was not made by a "trained programmer" (sic), and is getting better and better, also by people who have an interest in it, who have even refactored most of its code.

I ask you to redirect this repository to a repository of a GitHub organization (maybe, `/Seeks-Project/Seeks`), in the hope some others would contribute patches and even join to this organization.
