### ISSUE TITLE
error: variable 'google::protobuf::io::CodedOutputStream cos' has initializer but incomplete type

### ISSUE THREAD

**Issue by Quix0r** [beniz/seeks#6]
This error happens with latest master:

[...]
In file included from /usr/include/c++/4.7/ext/hash_map:61:0,
                 from ../../../../../seeks/src/plugins/query_capture/../../utils/stl_hash.h:23,
                 from ../../../../../seeks/src/plugins/query_capture/db_query_record.h:22,
                 from ../../../../../seeks/src/plugins/query_capture/db_query_record.cpp:20:
/usr/include/c++/4.7/backward/backward_warning.h:33:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
../../../../../seeks/src/plugins/query_capture/db_query_record.cpp: In member function 'virtual int seeks_plugins::db_query_record::serialize_compressed(std::string&) const':
../../../../../seeks/src/plugins/query_capture/db_query_record.cpp:306:50: error: variable 'google::protobuf::io::CodedOutputStream cos' has initializer but incomplete type
distcc[17211] ERROR: compile ../../../../../seeks/src/plugins/query_capture/db_query_record.cpp on localhost failed
make[5]: **\* [db_query_record.lo] Error 1

make[5]: Leaving directory `/home/quix0r/git/build/seeks/src/plugins/query_capture'
make[4]: **\* [all] Error 2

make[4]: Leaving directory `/home/quix0r/git/build/seeks/src/plugins/query_capture'
make[3]: **\* [all-recursive] Error 1

make[3]: Leaving directory `/home/quix0r/git/build/seeks/src/plugins'
make[2]: **\* [all-recursive] Error 1

make[2]: Leaving directory `/home/quix0r/git/build/seeks/src'
make[1]: **\* [all-recursive] Error 1

make[1]: Leaving directory `/home/quix0r/git/build/seeks'
make: **\* [all] Error 2

gcc-4.7 -v:
gcc version 4.7.3 (Debian 4.7.3-11)

**Comment by beniz** [comment]
See thread here:
https://aur.archlinux.org/packages/seeks/?setlang=hr

Summary:
try

```
./configure LDFLAGS="-Wl,--no-as-needed"
```

along with any other options you've added to the configure script.

**Comment by Quix0r** [comment]
This didn't help. Still same bug. :(

**Comment by beniz** [comment]
closed thanks to kamibo until told otherwise.
