### ISSUE TITLE
"Maximum number of open connections reached."

### ISSUE THREAD

**Issue by airon90** [beniz/seeks#9]
I built seeks-git from AUR repository of Arch Linux.
I load seeks in a terminal and "Maximum number of open connections reached." is displayed when I reach http://127.0.0.1:8250/.

**Comment by beniz** [comment]
This is a classic mistake: you are pointing your browser to http://127.0.0.1:8250/ instead of setting up your proxy. Go the preferences of your browser and setup the HTTP proxy instead.

**Comment by Quix0r** [comment]
He may wish to call the http server. Instead of 8250 write 8080 or what ever you have configured in httpserv-config + you need to set _automatic-proxy-disable 0_ to allow both proxy and http server be running. You may want to check if the plugin is activated (both in config file).
